# Generated by Django 4.0.4 on 2022-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_characterbonus_label_alter_vehiclestat_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctgpcup',
            name='image',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
